import fs from "fs";
import techOptions from "./techOptions.json";
import techOptFiles from "./techOptionsFiles.json";
import techOptPrep from "./techOptionsPrep.json";
import {
  getTechoptionsList,
  genTechOptionsDict,
  getFilesForLink,
  getLinksDict,
  clean,
  fillTechOptionsDict,
  filterPrep,
  sortDictByValue,
  sortDict,
} from "../update-tech-options/update-list.js";

test("getTechoptionsList()", () => {
  const result = getTechoptionsList();
  let expected = Object.values(techOptions);
  expected = expected.filter(function (item, pos) {
    return expected.indexOf(item) == pos;
  });
  expect(result.sort()).toEqual(expected.sort());
});

test("genTechOptionsDict()", () => {
  let optionList = Object.values(techOptions);
  optionList = optionList.filter(function (item, pos) {
    return optionList.indexOf(item) == pos;
  });
  const result = genTechOptionsDict(optionList);
  let expected = techOptions;
  expect(result).toEqual(expected);

  const result2 = genTechOptionsDict(optionList, {});
  let expected2 = {
    "1c": "1C",
    "1c-bitrix": "1C-Bitrix",
    "1cbitrix": "1C-Bitrix",
    "a-frame": "A-Frame",
    actionscript: "Actionscript",
    ada: "Ada",
    adb: "Ada",
    adobe: "Adobe",
    ads: "Ada",
    advancedinstaller: "AdvancedInstaller",
    adventuregamestudio: "AdventureGameStudio",
    aframe: "A-Frame",
    agda: "Agda",
    al: "AL",
    alteraquartusii: "AlteraQuartusII",
    altium: "Altium",
    amplify: "Amplify",
    android: "Android",
    androidstudio: "AndroidStudio",
    angular: "Angular",
    anjuta: "Anjuta",
    ansible: "Ansible",
    ansibletower: "AnsibleTower",
    apachecordova: "ApacheCordova",
    apachehadoop: "ApacheHadoop",
    appbuilder: "AppBuilder",
    appceleratortitanium: "AppceleratorTitanium",
    appcode: "AppCode",
    "appcode+all": "AppCode+all",
    "appcode+iml": "AppCode+iml",
    appcodeall: "AppCode+all",
    appcodeiml: "AppCode+iml",
    appengine: "AppEngine",
    aptanastudio: "AptanaStudio",
    arcanist: "Arcanist",
    archive: "Archive",
    archives: "Archives",
    archlinuxpackages: "ArchLinuxPackages",
    as: "Actionscript",
    asdf: "asdf",
    asm: "Assembler",
    "asp.netcore": "ASPNETCore",
    aspnetcore: "ASPNETCore",
    assembler: "Assembler",
    astro: "Astro",
    ate: "ATE",
    atmelstudio: "AtmelStudio",
    ats: "ATS",
    audio: "Audio",
    autohotkey: "Autohotkey",
    automationstudio: "AutomationStudio",
    autotools: "Autotools",
    "autotools+strict": "Autotools+strict",
    autotoolsstrict: "Autotools+strict",
    awr: "AWR",
    azurefunctions: "AzureFunctions",
    azurite: "Azurite",
    backup: "Backup",
    ballerina: "Ballerina",
    basercms: "baserCMS",
    basic: "Basic",
    batch: "Batch",
    bazaar: "Bazaar",
    bazel: "Bazel",
    bitrise: "Bitrise",
    bitrix: "Bitrix",
    bittorrent: "BitTorrent",
    blackbox: "Blackbox",
    blender: "Blender",
    bloop: "Bloop",
    bluej: "bluej",
    bookdown: "Bookdown",
    bower: "Bower",
    bricxcc: "BricxCC",
    buck: "Buck",
    c: "C",
    "c#": "Csharp",
    "c++": "C++",
    cake: "Cake",
    cakephp: "CakePHP",
    cakephp2: "CakePHP2",
    cakephp3: "CakePHP3",
    calabash: "Calabash",
    carthage: "Carthage",
    cbp: "CodeBlocks",
    certificates: "certificates",
    ceylon: "Ceylon",
    cfwheels: "CFWheels",
    chefcookbook: "ChefCookbook",
    chocolatey: "Chocolatey",
    circuitpython: "CircuitPython",
    clean: "Clean",
    clion: "CLion",
    "clion+all": "CLion+all",
    "clion+iml": "CLion+iml",
    clionall: "CLion+all",
    clioniml: "CLion+iml",
    clojure: "Clojure",
    cloud9: "Cloud9",
    cmake: "CMake",
    cocoapods: "CocoaPods",
    cocos2dx: "Cocos2dx",
    cocoscreator: "CocosCreator",
    codeblocks: "CodeBlocks",
    codecomposerstudio: "CodeComposerStudio",
    codeigniter: "CodeIgniter",
    codeio: "Codeio",
    codekit: "CodeKit",
    codesniffer: "CodeSniffer",
    coffeescript: "CoffeeScript",
    commonlisp: "CommonLisp",
    compodoc: "Compodoc",
    composer: "Composer",
    compressed: "Compressed",
    compressedarchive: "CompressedArchive",
    compression: "Compression",
    conan: "Conan",
    concrete5: "Concrete5",
    coq: "Coq",
    cordova: "Cordova",
    cpluplus: "C++",
    cpp: "C++",
    craftcms: "CraftCMS",
    crashlytics: "Crashlytics",
    crbasic: "CRBasic",
    crossbar: "Crossbar",
    crystal: "Crystal",
    "cs-cart": "CS-Cart",
    cscart: "CS-Cart",
    csharp: "Csharp",
    cuda: "CUDA",
    cvs: "CVS",
    cypressio: "CypressIO",
    d: "D",
    dart: "Dart",
    darteditor: "DartEditor",
    data: "Data",
    database: "Database",
    datarecovery: "DataRecovery",
    dbeaver: "DBeaver",
    dbt: "dbt",
    defold: "Defold",
    delphi: "Delphi",
    deno: "Deno",
    dframe: "Dframe",
    diff: "Diff",
    direnv: "direnv",
    diskimage: "DiskImage",
    django: "Django",
    dm: "DM",
    docfx: "DocFx",
    docpress: "Docpress",
    docusaurus: "Docusaurus",
    docz: "Docz",
    dotenv: "dotenv",
    dotfilessh: "DotfilesSh",
    dotnetcore: "DotnetCore",
    dotsettings: "DotSettings",
    doxygen: "Doxygen",
    dreamweaver: "Dreamweaver",
    dropbox: "Dropbox",
    drupal: "Drupal",
    drupal7: "Drupal7",
    drupal8: "Drupal8",
    e2studio: "e2studio",
    eagle: "Eagle",
    easybook: "easybook",
    eclipse: "Eclipse",
    eiffelstudio: "EiffelStudio",
    elasticbeanstalk: "ElasticBeanstalk",
    elisp: "Elisp",
    elixir: "Elixir",
    elm: "Elm",
    emacs: "Emacs",
    ember: "Ember",
    ensime: "Ensime",
    episerver: "EPiServer",
    erlang: "Erlang",
    espresso: "Espresso",
    executable: "Executable",
    exercism: "Exercism",
    expressionengine: "ExpressionEngine",
    extjs: "ExtJs",
    "f#": "fsharp",
    fancy: "Fancy",
    fastlane: "fastlane",
    finale: "Finale",
    firebase: "Firebase",
    fish: "Fish",
    flashbuilder: "FlashBuilder",
    flask: "Flask",
    flatpak: "Flatpak",
    flex: "Flex",
    flexbuilder: "FlexBuilder",
    floobits: "floobits",
    flutter: "Flutter",
    font: "Font",
    fontforge: "FontForge",
    forcedotcom: "ForceDotCom",
    forgegradle: "ForgeGradle",
    fortran: "Fortran",
    freecad: "FreeCad",
    freepascal: "FreePascal",
    fsharp: "fsharp",
    fuelphp: "FuelPHP",
    fusetools: "FuseTools",
    games: "Games",
    gatsby: "Gatsby",
    gcov: "Gcov",
    genero4gl: "Genero4GL",
    geth: "Geth",
    ggts: "GGTS",
    gis: "GIS",
    git: "Git",
    gitbook: "GitBook",
    go: "Go",
    godot: "Godot",
    goland: "GoLand",
    "goland+all": "GoLand+all",
    "goland+iml": "GoLand+iml",
    golandall: "GoLand+all",
    golandiml: "GoLand+iml",
    goodsync: "GoodSync",
    gpg: "GPG",
    gradle: "Gradle",
    grails: "Grails",
    greenfoot: "greenfoot",
    groovy: "Groovy",
    grunt: "grunt",
    gwt: "GWT",
    haskell: "Haskell",
    helm: "Helm",
    hexo: "Hexo",
    hol: "HOL",
    homeassistant: "HomeAssistant",
    homebrew: "Homebrew",
    hs: "Haskell",
    hsp: "HSP",
    hugo: "Hugo",
    hyperledgercomposer: "HyperledgerComposer",
    iar: "IAR",
    iar_ewarm: "IAR_EWARM",
    iarembeddedworkbench: "IAREmbeddedWorkBench",
    iarewarm: "IAR_EWARM",
    idapro: "IDAPro",
    idris: "Idris",
    igorpro: "IGORPro",
    images: "Images",
    infer: "infer",
    inforcms: "InforCMS",
    inforcrm: "InforCRM",
    intellij: "Intellij",
    "intellij+all": "Intellij+all",
    "intellij+iml": "Intellij+iml",
    intellijall: "Intellij+all",
    intellijiml: "Intellij+iml",
    ionic3: "Ionic3",
    ipynb: "JupyterNotebooks",
    jabref: "JabRef",
    janet: "Janet",
    java: "Java",
    jboss: "JBoss",
    "jboss-4-2-3-ga": "JBoss-4-2-3-GA",
    "jboss-6-x": "JBoss-6-x",
    jboss4: "JBoss4",
    jboss423ga: "JBoss-4-2-3-GA",
    jboss6: "JBoss6",
    jboss6x: "JBoss-6-x",
    jdeveloper: "JDeveloper",
    jekyll: "Jekyll",
    jenv: "JEnv",
    jetbrains: "JetBrains",
    "jetbrains+all": "JetBrains+all",
    "jetbrains+iml": "JetBrains+iml",
    jetbrainsall: "JetBrains+all",
    jetbrainsiml: "JetBrains+iml",
    jgiven: "JGiven",
    jigsaw: "Jigsaw",
    jl: "Julia",
    jmeter: "JMeter",
    joe: "Joe",
    joomla: "Joomla",
    jsonnet: "Jsonnet",
    jspm: "jspm",
    jsx: "react",
    julia: "Julia",
    jupyternotebooks: "JupyterNotebooks",
    justcode: "JustCode",
    kaldi: "kaldi",
    kate: "Kate",
    kdevelop4: "KDevelop4",
    kdiff3: "KDiff3",
    keil: "Keil",
    kentico: "Kentico",
    keystonejs: "KeystoneJS",
    kicad: "KiCad",
    kirby2: "Kirby2",
    kirby3: "Kirby3",
    kobalt: "Kobalt",
    kohana: "Kohana",
    komodoedit: "KomodoEdit",
    konyvisualizer: "KonyVisualizer",
    kotlin: "Kotlin",
    kt: "Kotlin",
    labview: "LabVIEW",
    labviewnxg: "LabVIEWNXG",
    lamp: "LAMP",
    laravel: "Laravel",
    latex: "LaTeX",
    lazarus: "Lazarus",
    leiningen: "Leiningen",
    lemonstand: "LemonStand",
    less: "Less",
    liberosoc: "LiberoSOC",
    "librarian-chef": "librarian-chef",
    librarianchef: "librarian-chef",
    libreoffice: "LibreOffice",
    lighthouseci: "LighthouseCI",
    lilypond: "Lilypond",
    linux: "Linux",
    lithium: "Lithium",
    localstack: "LocalStack",
    logtalk: "Logtalk",
    lsspice: "LSspice",
    ltspice: "LTspice",
    lua: "Lua",
    lyx: "LyX",
    macos: "macOS",
    magento: "Magento",
    magento1: "Magento1",
    magento2: "Magento2",
    "magic-xpa": "Magic-xpa",
    magicxpa: "Magic-xpa",
    matlab: "MATLAB",
    maven: "Maven",
    mavensmate: "MavensMate",
    mdbook: "MdBook",
    mean: "MEAN",
    mercurial: "Mercurial",
    mercury: "Mercury",
    meson: "Meson",
    metals: "Metals",
    metalsmith: "Metalsmith",
    metaprogrammingsystem: "MetaProgrammingSystem",
    meteor: "Meteor",
    meteorjs: "MeteorJS",
    microsoftoffice: "MicrosoftOffice",
    mikroc: "MikroC",
    mill: "Mill",
    moban: "Moban",
    modelsim: "ModelSim",
    modx: "MODX",
    momentics: "Momentics",
    monodevelop: "MonoDevelop",
    mplabx: "MPLabX",
    mps: "MetaProgrammingSystem",
    mule: "mule",
    nanoc: "Nanoc",
    nativescript: "NativeScript",
    ncrunch: "NCrunch",
    nesc: "NesC",
    netbeans: "NetBeans",
    nette: "Nette",
    "next.js": "NextJS",
    nextjs: "NextJS",
    nikola: "Nikola",
    nim: "Nim",
    ninja: "Ninja",
    node: "Node",
    nodechakratimetraveldebug: "NodeChakraTimeTravelDebug",
    nohup: "Nohup",
    notepadpp: "NotepadPP",
    nova: "nova",
    now: "now",
    npp: "NotepadPP",
    "nuxt.js": "NuxtJS",
    nuxtjs: "NuxtJS",
    nwjs: "NWjs",
    "objective-c": "Objective-C",
    objectivec: "Objective-C",
    obsidian: "Obsidian",
    ocaml: "OCaml",
    octave: "Octave",
    octobercms: "OctoberCms",
    opa: "Opa",
    opencart: "OpenCart",
    opencv: "OpenCV",
    openfoam: "OpenFOAM",
    openframeworks: "OpenFrameworks",
    "openframeworks+visualstudio": "OpenFrameworks+VisualStudio",
    openframeworksvisualstudio: "OpenFrameworks+VisualStudio",
    oracleforms: "OracleForms",
    orcad: "OrCAD",
    osx: "OSX",
    otto: "Otto",
    oxideshop: "OxidEshop",
    oxygenxmleditor: "oXygenXMLEditor",
    p6: "Perl6",
    packer: "Packer",
    pants: "Pants",
    particle: "Particle",
    patch: "Patch",
    pawn: "PAWN",
    perl: "Perl",
    perl6: "Perl6",
    ph7cms: "pH7CMS",
    phalcon: "Phalcon",
    phoenix: "Phoenix",
    "php-cs-fixer": "PHP-CS-Fixer",
    phpcodesniffer: "PHPCodeSniffer",
    phpcsfixer: "PHP-CS-Fixer",
    phpstorm: "PhpStorm",
    "phpstorm+all": "PhpStorm+all",
    "phpstorm+iml": "PhpStorm+iml",
    phpstormall: "PhpStorm+all",
    phpstormiml: "PhpStorm+iml",
    phpunit: "PHPUnit",
    pico8: "pico8",
    pimcore: "Pimcore",
    pimcore4: "Pimcore4",
    pimcore5: "Pimcore5",
    pinegrow: "PineGrow",
    pl: "Perl",
    platformio: "PlatformIO",
    playframework: "PlayFramework",
    plone: "Plone",
    polymer: "Polymer",
    powershell: "PowerShell",
    "premake-gmake": "premake-gmake",
    premakegmake: "premake-gmake",
    prepros: "Prepros",
    prestashop: "Prestashop",
    processing: "Processing",
    progressabl: "ProgressABL",
    ps: "PowerShell",
    psoccreator: "PSoCCreator",
    pulumi: "Pulumi",
    "pulumi+stacks": "Pulumi+stacks",
    pulumistacks: "Pulumi+stacks",
    puppet: "Puppet",
    "puppet-librarian": "puppet-librarian",
    puppetlibrarian: "puppet-librarian",
    purebasic: "PureBasic",
    purescript: "PureScript",
    putty: "PuTTY",
    pvs: "PVS",
    pycharm: "PyCharm",
    "pycharm+all": "PyCharm+all",
    "pycharm+iml": "PyCharm+iml",
    pycharmall: "PyCharm+all",
    pycharmiml: "PyCharm+iml",
    pydev: "pydev",
    python: "Python",
    pythonvanilla: "PythonVanilla",
    qml: "QML",
    qooxdoo: "Qooxdoo",
    qt: "Qt",
    qtcreator: "QtCreator",
    r: "R",
    racket: "Racket",
    rails: "Rails",
    rb: "Ruby",
    rbrubymin: "RubyMine",
    "rbrubymin+all": "RubyMine+all",
    "rbrubymin+iml": "RubyMine+iml",
    react: "react",
    "react.js": "react",
    reactjs: "react",
    reactnative: "ReactNative",
    reasonml: "Reasonml",
    red: "Red",
    redcar: "Redcar",
    redis: "Redis",
    remix: "Remix",
    "remix+arc": "Remix+Arc",
    "remix+cloudflarepages": "Remix+CloudflarePages",
    "remix+cloudflareworkers": "Remix+CloudflareWorkers",
    "remix+netlify": "Remix+Netlify",
    "remix+vercel": "Remix+Vercel",
    remixarc: "Remix+Arc",
    remixcloudflarepages: "Remix+CloudflarePages",
    remixcloudflareworkers: "Remix+CloudflareWorkers",
    remixnetlify: "Remix+Netlify",
    remixvercel: "Remix+Vercel",
    renpy: "Renpy",
    replit: "replit",
    retool: "retool",
    rhodesrhomobile: "RhodesRhomobile",
    rider: "Rider",
    rkt: "Racket",
    robotframework: "robotframework",
    root: "ROOT",
    ros: "ROS",
    ros2: "ROS2",
    rs: "Rust",
    ruby: "Ruby",
    rubymine: "RubyMine",
    "rubymine+all": "RubyMine+all",
    "rubymine+iml": "RubyMine+iml",
    rubymineall: "RubyMine+all",
    rubymineiml: "RubyMine+iml",
    rust: "Rust",
    "rust-analyzer": "rust-analyzer",
    rustanalyzer: "rust-analyzer",
    salesforce: "Salesforce",
    salesforcedx: "SalesforceDX",
    sam: "SAM",
    "sam+config": "SAM+config",
    samconfig: "SAM+config",
    sas: "SAS",
    sass: "Sass",
    sbt: "SBT",
    scala: "Scala",
    sch: "Eagle",
    scheme: "Scheme",
    scm: "Scheme",
    scons: "SCons",
    scrivener: "Scrivener",
    sdcc: "Sdcc",
    seamgen: "SeamGen",
    senchatouch: "SenchaTouch",
    serverless: "Serverless",
    shopware: "Shopware",
    silverstripe: "Silverstripe",
    sketchup: "SketchUp",
    skp: "SketchUp",
    slickedit: "SlickEdit",
    smalltalk: "Smalltalk",
    snap: "Snap",
    snapcraft: "Snapcraft",
    snyk: "Snyk",
    solidity: "Solidity",
    soliditytruffle: "SolidityTruffle",
    sonar: "Sonar",
    sonarqube: "SonarQube",
    sourcepawn: "SourcePawn",
    spark: "Spark",
    specflow: "SpecFlow",
    splunk: "Splunk",
    spreadsheet: "Spreadsheet",
    ssh: "SSH",
    standardml: "StandardML",
    stata: "Stata",
    stdlib: "StdLib",
    stella: "Stella",
    stellar: "Stellar",
    storybookjs: "StorybookJs",
    strapi: "Strapi",
    stylus: "Stylus",
    sublimetext: "SublimeText",
    sugarcrm: "SugarCRM",
    svelte: "Svelte",
    svn: "SVN",
    swift: "Swift",
    swiftpackagemanager: "SwiftPackageManager",
    swiftpm: "SwiftPM",
    symfony: "Symfony",
    symphonycms: "SymphonyCMS",
    synology: "Synology",
    synopsysvcs: "SynopsysVCS",
    tags: "Tags",
    tarmainstallmate: "TarmaInstallMate",
    terraform: "Terraform",
    terragrunt: "Terragrunt",
    test: "Test",
    testcomplete: "TestComplete",
    testinfra: "Testinfra",
    tex: "TeX",
    text: "Text",
    textmate: "TextMate",
    textpattern: "Textpattern",
    tf: "Terraform",
    "theos-tweak": "THEOS-Tweak",
    theostweak: "THEOS-Tweak",
    thinkphp: "ThinkPHP",
    tla: "TLA+",
    "tla+": "TLA+",
    toit: "Toit",
    tortoisegit: "TortoiseGit",
    tower: "Tower",
    turbo: "Turbo",
    turbogears2: "TurboGears2",
    twincat3: "TwinCAT3",
    tye: "Tye",
    typings: "Typings",
    typo3: "Typo3",
    "typo3-composer": "TYPO3-composer",
    typo3composer: "TYPO3-composer",
    umbraco: "Umbraco",
    unity: "Unity",
    unrealengine: "UnrealEngine",
    vaadin: "Vaadin",
    vagrant: "Vagrant",
    valgrind: "Valgrind",
    vapor: "Vapor",
    vb: "VisualBasic",
    vcpkg: "vcpkg",
    venv: "venv",
    vercel: "Vercel",
    vertx: "Vertx",
    video: "Video",
    vim: "Vim",
    virtualenv: "VirtualEnv",
    virtuoso: "Virtuoso",
    visualbasic: "VisualBasic",
    visualstudio: "VisualStudio",
    visualstudiocode: "VisualStudioCode",
    vivado: "Vivado",
    vlab: "VLab",
    vrealizeorchestrator: "vRealizeOrchestrator",
    vs: "vs",
    vscode: "VisualStudioCode",
    vue: "Vue",
    "vue.js": "Vuejs",
    vuejs: "Vuejs",
    vvvv: "VVVV",
    waf: "Waf",
    wakanda: "Wakanda",
    web: "Web",
    webmethods: "WebMethods",
    webstorm: "WebStorm",
    "webstorm+all": "WebStorm+all",
    "webstorm+iml": "WebStorm+iml",
    webstormall: "WebStorm+all",
    webstormiml: "WebStorm+iml",
    werckercli: "WerckerCLI",
    windows: "Windows",
    wintersmith: "Wintersmith",
    wordpress: "WordPress",
    wp: "WordPress",
    wyam: "Wyam",
    xamarinstudio: "XamarinStudio",
    xcode: "Xcode",
    xcodeinjection: "XcodeInjection",
    xilinx: "Xilinx",
    xilinxise: "XilinxISE",
    xilinxvivado: "XilinxVivado",
    xill: "Xill",
    xmake: "xmake",
    xojo: "Xojo",
    xtext: "XText",
    y86: "Y86",
    yalc: "yalc",
    yarn: "yarn",
    yeoman: "Yeoman",
    yii: "Yii",
    yii2: "Yii2",
    zendframework: "ZendFramework",
    zephir: "Zephir",
    zig: "zig",
    zsh: "Zsh",
    zukencr8000: "ZukenCR8000",
  };
  expect(result).toEqual(expected2);
});

test("clean()", () => {
  // Test case 1
  let input = "React";
  const result1 = clean(input);
  let expected1 = "react";
  expect(result1).toEqual(expected1);

  // Test case 2
  let input2 = "ASP.NETCORE++";
  const result2 = clean(input2);
  let expected2 = "aspnetcore";
  expect(result2).toEqual(expected2);
});

test("fillTechOptionsDict()", () => {
  // Test case 1
  const result1 = fillTechOptionsDict(techOptPrep, getTechoptionsList());
  let expected1 = techOptions;
  expect(result1).toEqual(expected1);

  // Test case 2
  let techOptPrep2 = {
    adb: "Ada",
    ads: "Ada",
    as: "Actionscript",
    asm: "Assembler",
    "asp.netcore": "ASPNETCore",
    cbp: "CodeBlocks",
    cpluplus: "C++",
    cpp: "C++",
    "c#": "Csharp",
    sch: "Eagle",
  };
  let allTechOptions2 = ["As", "Asp.netcore", "CbP", "Sch++"];

  const result2 = fillTechOptionsDict(techOptPrep2, allTechOptions2);
  let expected2 = {
    adb: "Ada",
    ads: "Ada",
    as: "As",
    asm: "Assembler",
    "asp.netcore": "Asp.netcore",
    aspnetcore: "Asp.netcore",
    "c#": "Csharp",
    cbp: "CbP",
    cpluplus: "C++",
    cpp: "C++",
    sch: "Eagle",
    "sch++": "Sch++",
  };
  expect(result2).toEqual(expected2);
});

test("filterPrep()", () => {
  // Test case 1
  const result1 = filterPrep(techOptPrep, getTechoptionsList());
  let expected1 = {
    "1c-bitrix": "1C-Bitrix",
    "a-frame": "A-Frame",
    adb: "Ada",
    ads: "Ada",
    "appcode+all": "AppCode+all",
    "appcode+iml": "AppCode+iml",
    as: "Actionscript",
    asm: "Assembler",
    "asp.netcore": "ASPNETCore",
    "autotools+strict": "Autotools+strict",
    "c#": "Csharp",
    "c++": "C++",
    cbp: "CodeBlocks",
    "clion+all": "CLion+all",
    "clion+iml": "CLion+iml",
    cpluplus: "C++",
    cpp: "C++",
    "cs-cart": "CS-Cart",
    "f#": "fsharp",
    "goland+all": "GoLand+all",
    "goland+iml": "GoLand+iml",
    hs: "Haskell",
    iar_ewarm: "IAR_EWARM",
    "intellij+all": "Intellij+all",
    "intellij+iml": "Intellij+iml",
    ipynb: "JupyterNotebooks",
    "jboss-4-2-3-ga": "JBoss-4-2-3-GA",
    "jboss-6-x": "JBoss-6-x",
    "jetbrains+all": "JetBrains+all",
    "jetbrains+iml": "JetBrains+iml",
    jl: "Julia",
    jsx: "react",
    kt: "Kotlin",
    "librarian-chef": "librarian-chef",
    "magic-xpa": "Magic-xpa",
    mps: "MetaProgrammingSystem",
    "next.js": "NextJS",
    npp: "NotepadPP",
    "nuxt.js": "NuxtJS",
    "objective-c": "Objective-C",
    "openframeworks+visualstudio": "OpenFrameworks+VisualStudio",
    p6: "Perl6",
    "php-cs-fixer": "PHP-CS-Fixer",
    "phpstorm+all": "PhpStorm+all",
    "phpstorm+iml": "PhpStorm+iml",
    pl: "Perl",
    "premake-gmake": "premake-gmake",
    ps: "PowerShell",
    "pulumi+stacks": "Pulumi+stacks",
    "puppet-librarian": "puppet-librarian",
    "pycharm+all": "PyCharm+all",
    "pycharm+iml": "PyCharm+iml",
    rb: "Ruby",
    rbrubymin: "RubyMine",
    "rbrubymin+all": "RubyMine+all",
    "rbrubymin+iml": "RubyMine+iml",
    "react.js": "react",
    reactjs: "react",
    "remix+arc": "Remix+Arc",
    "remix+cloudflarepages": "Remix+CloudflarePages",
    "remix+cloudflareworkers": "Remix+CloudflareWorkers",
    "remix+netlify": "Remix+Netlify",
    "remix+vercel": "Remix+Vercel",
    rkt: "Racket",
    rs: "Rust",
    "rubymine+all": "RubyMine+all",
    "rubymine+iml": "RubyMine+iml",
    "rust-analyzer": "rust-analyzer",
    "sam+config": "SAM+config",
    sch: "Eagle",
    scm: "Scheme",
    skp: "SketchUp",
    tf: "Terraform",
    "theos-tweak": "THEOS-Tweak",
    "tla+": "TLA+",
    "typo3-composer": "TYPO3-composer",
    vb: "VisualBasic",
    vscode: "VisualStudioCode",
    "vue.js": "Vuejs",
    "webstorm+all": "WebStorm+all",
    "webstorm+iml": "WebStorm+iml",
    wp: "WordPress",
  };
  expect(result1).toEqual(expected1);

  // Test case 2
  let allTechOptions2 = [
    "As",
    "Asp.netcore",
    "C++",
    "CbP",
    "Sch++",
    "Actionscript",
    "Assembler",
    "ASPNETCore",
    "CodeBlocks",
    "Csharp",
    "Eagle",
  ];
  let techOptPrep2 = {
    adb: "Ada",
    ads: "Ada",
    as: "Actionscript",
    asm: "Assembler",
    "asp.netcore": "ASPNETCore",
    cbp: "CodeBlocks",
    cpluplus: "C++",
    cpp: "C++",
    "c#": "Csharp",
    sch: "Eagle",
  };
  const result2 = filterPrep(techOptPrep2, allTechOptions2);
  let expected2 = {
    asm: "Assembler",
    "asp.netcore": "ASPNETCore",
    "c#": "Csharp",
    cpluplus: "C++",
    cpp: "C++",
  };
  expect(result2).toEqual(expected2);
});

test("sortDictByValue()", () => {
  // Test case 1
  let input1 = {
    a: "3",
    b: "1",
    c: "2",
  };
  const result1 = sortDictByValue(input1);
  let expected1 = {
    b: "1",
    c: "2",
    a: "3",
  };
  expect(result1).toEqual(expected1);

  // Test case 2
  let input2 = {
    x: "10",
    y: "5",
    z: "7",
  };
  const result2 = sortDictByValue(input2);
  let expected2 = {
    y: "5",
    z: "7",
    x: "10",
  };
  expect(result2).toEqual(expected2);
});

test("getLinksDict()", () => {
  const result = getLinksDict();
  let expected = techOptFiles;
  expect(result).toEqual(expected);
});

test("getFilesForLink()", () => {
  let files = fs.readdirSync("./templates", {
    withFileTypes: true,
  });
  const result = getFilesForLink(files, "ReactNative");
  let expected = [
    "Android.gitignore",
    "Android.patch",
    "Buck.gitignore",
    "Gradle.gitignore",
    "Gradle.patch",
    "Linux.gitignore",
    "Node.gitignore",
    "Node.patch",
    "Xcode.gitignore",
    "Xcode.patch",
    "ReactNative.gitignore",
    "macOS.gitignore",
    "macOS.patch",
  ];
  expect(result.sort()).toEqual(expected.sort());
});
