import fs from "fs";
import techOptions from "./assets/techOptions.json";
import techOptFiles from "./assets/techOptionsFiles.json";
import techOptPrep from "./assets/techOptionsPrep.json";
import {
  getTechoptionsList,
  genTechOptionsDict,
  getFilesForLink,
  getLinksDict,
  clean,
  fillTechOptionsDict,
  filterPrep,
  sortDictByValue,
  sortDict,
  sortFiles,
} from "../update-tech-options/update-list.js";

describe("getTechoptionsList()", () => {
  test("getTechoptionsList()", () => {
    const result = getTechoptionsList();

    let expected = Object.values(techOptions);
    expected = expected.filter(function (item, pos) {
      return expected.indexOf(item) == pos;
    });

    expect(result.sort()).toEqual(expected.sort());
  });
});

describe("genTechOptionsDict()", () => {
  let optionList: string[];

  beforeAll(() => {
    optionList = Object.values(techOptions);
    optionList = optionList.filter(function (item, pos) {
      return optionList.indexOf(item) == pos;
    });
  });

  test("genTechOptionsDict()", () => {
    const result = genTechOptionsDict(optionList);

    let expected = techOptions;

    expect(result).toEqual(expected);
  });

  test("genTechOptionsDict()", () => {
    const result2 = genTechOptionsDict(optionList, {});

    let expected2 = {
      "1c": "1C",
      "1c-bitrix": "1C-Bitrix",
      "1cbitrix": "1C-Bitrix",
      "a-frame": "A-Frame",
      actionscript: "Actionscript",
      ada: "Ada",
      adobe: "Adobe",
      advancedinstaller: "AdvancedInstaller",
      adventuregamestudio: "AdventureGameStudio",
      aframe: "A-Frame",
      agda: "Agda",
      al: "AL",
      alteraquartusii: "AlteraQuartusII",
      altium: "Altium",
      amplify: "Amplify",
      android: "Android",
      androidstudio: "AndroidStudio",
      angular: "Angular",
      anjuta: "Anjuta",
      ansible: "Ansible",
      ansibletower: "AnsibleTower",
      apachecordova: "ApacheCordova",
      apachehadoop: "ApacheHadoop",
      appbuilder: "AppBuilder",
      appceleratortitanium: "AppceleratorTitanium",
      appcode: "AppCode",
      "appcode+all": "AppCode+all",
      "appcode+iml": "AppCode+iml",
      appcodeall: "AppCode+all",
      appcodeiml: "AppCode+iml",
      appengine: "AppEngine",
      aptanastudio: "AptanaStudio",
      arcanist: "Arcanist",
      archive: "Archive",
      archives: "Archives",
      archlinuxpackages: "ArchLinuxPackages",
      asdf: "asdf",
      aspnetcore: "ASPNETCore",
      assembler: "Assembler",
      astro: "Astro",
      ate: "ATE",
      atmelstudio: "AtmelStudio",
      ats: "ATS",
      audio: "Audio",
      autohotkey: "Autohotkey",
      automationstudio: "AutomationStudio",
      autotools: "Autotools",
      "autotools+strict": "Autotools+strict",
      autotoolsstrict: "Autotools+strict",
      awr: "AWR",
      azurefunctions: "AzureFunctions",
      azurite: "Azurite",
      backup: "Backup",
      ballerina: "Ballerina",
      basercms: "baserCMS",
      basic: "Basic",
      batch: "Batch",
      bazaar: "Bazaar",
      bazel: "Bazel",
      bitrise: "Bitrise",
      bitrix: "Bitrix",
      bittorrent: "BitTorrent",
      blackbox: "Blackbox",
      blender: "Blender",
      bloop: "Bloop",
      bluej: "bluej",
      bookdown: "Bookdown",
      bower: "Bower",
      bricxcc: "BricxCC",
      buck: "Buck",
      c: "C",
      "c++": "C++",
      cake: "Cake",
      cakephp: "CakePHP",
      cakephp2: "CakePHP2",
      cakephp3: "CakePHP3",
      calabash: "Calabash",
      carthage: "Carthage",
      certificates: "certificates",
      ceylon: "Ceylon",
      cfwheels: "CFWheels",
      chefcookbook: "ChefCookbook",
      chocolatey: "Chocolatey",
      circuitpython: "CircuitPython",
      clean: "Clean",
      clion: "CLion",
      "clion+all": "CLion+all",
      "clion+iml": "CLion+iml",
      clionall: "CLion+all",
      clioniml: "CLion+iml",
      clojure: "Clojure",
      cloud9: "Cloud9",
      cmake: "CMake",
      cocoapods: "CocoaPods",
      cocos2dx: "Cocos2dx",
      cocoscreator: "CocosCreator",
      codeblocks: "CodeBlocks",
      codecomposerstudio: "CodeComposerStudio",
      codeigniter: "CodeIgniter",
      codeio: "Codeio",
      codekit: "CodeKit",
      codesniffer: "CodeSniffer",
      coffeescript: "CoffeeScript",
      commonlisp: "CommonLisp",
      compodoc: "Compodoc",
      composer: "Composer",
      compressed: "Compressed",
      compressedarchive: "CompressedArchive",
      compression: "Compression",
      conan: "Conan",
      concrete5: "Concrete5",
      coq: "Coq",
      cordova: "Cordova",
      craftcms: "CraftCMS",
      crashlytics: "Crashlytics",
      crbasic: "CRBasic",
      crossbar: "Crossbar",
      crystal: "Crystal",
      "cs-cart": "CS-Cart",
      cscart: "CS-Cart",
      csharp: "Csharp",
      cuda: "CUDA",
      cvs: "CVS",
      cypressio: "CypressIO",
      d: "D",
      dart: "Dart",
      darteditor: "DartEditor",
      data: "Data",
      database: "Database",
      datarecovery: "DataRecovery",
      dbeaver: "DBeaver",
      dbt: "dbt",
      defold: "Defold",
      delphi: "Delphi",
      deno: "Deno",
      dframe: "Dframe",
      diff: "Diff",
      direnv: "direnv",
      diskimage: "DiskImage",
      django: "Django",
      dm: "DM",
      docfx: "DocFx",
      docpress: "Docpress",
      docusaurus: "Docusaurus",
      docz: "Docz",
      dotenv: "dotenv",
      dotfilessh: "DotfilesSh",
      dotnetcore: "DotnetCore",
      dotsettings: "DotSettings",
      doxygen: "Doxygen",
      dreamweaver: "Dreamweaver",
      dropbox: "Dropbox",
      drupal: "Drupal",
      drupal7: "Drupal7",
      drupal8: "Drupal8",
      e2studio: "e2studio",
      eagle: "Eagle",
      easybook: "easybook",
      eclipse: "Eclipse",
      eiffelstudio: "EiffelStudio",
      elasticbeanstalk: "ElasticBeanstalk",
      elisp: "Elisp",
      elixir: "Elixir",
      elm: "Elm",
      emacs: "Emacs",
      ember: "Ember",
      ensime: "Ensime",
      episerver: "EPiServer",
      erlang: "Erlang",
      espresso: "Espresso",
      executable: "Executable",
      exercism: "Exercism",
      expressionengine: "ExpressionEngine",
      extjs: "ExtJs",
      fancy: "Fancy",
      fastlane: "fastlane",
      finale: "Finale",
      firebase: "Firebase",
      fish: "Fish",
      flashbuilder: "FlashBuilder",
      flask: "Flask",
      flatpak: "Flatpak",
      flex: "Flex",
      flexbuilder: "FlexBuilder",
      floobits: "floobits",
      flutter: "Flutter",
      font: "Font",
      fontforge: "FontForge",
      forcedotcom: "ForceDotCom",
      forgegradle: "ForgeGradle",
      fortran: "Fortran",
      freecad: "FreeCad",
      freepascal: "FreePascal",
      fsharp: "fsharp",
      fuelphp: "FuelPHP",
      fusetools: "FuseTools",
      games: "Games",
      gatsby: "Gatsby",
      gcov: "Gcov",
      genero4gl: "Genero4GL",
      geth: "Geth",
      ggts: "GGTS",
      gis: "GIS",
      git: "Git",
      gitbook: "GitBook",
      go: "Go",
      godot: "Godot",
      goland: "GoLand",
      "goland+all": "GoLand+all",
      "goland+iml": "GoLand+iml",
      golandall: "GoLand+all",
      golandiml: "GoLand+iml",
      goodsync: "GoodSync",
      gpg: "GPG",
      gradle: "Gradle",
      grails: "Grails",
      greenfoot: "greenfoot",
      groovy: "Groovy",
      grunt: "grunt",
      gwt: "GWT",
      haskell: "Haskell",
      helm: "Helm",
      hexo: "Hexo",
      hol: "HOL",
      homeassistant: "HomeAssistant",
      homebrew: "Homebrew",
      hsp: "HSP",
      hugo: "Hugo",
      hyperledgercomposer: "HyperledgerComposer",
      iar: "IAR",
      iar_ewarm: "IAR_EWARM",
      iarembeddedworkbench: "IAREmbeddedWorkBench",
      iarewarm: "IAR_EWARM",
      idapro: "IDAPro",
      idris: "Idris",
      igorpro: "IGORPro",
      images: "Images",
      infer: "infer",
      inforcms: "InforCMS",
      inforcrm: "InforCRM",
      intellij: "Intellij",
      "intellij+all": "Intellij+all",
      "intellij+iml": "Intellij+iml",
      intellijall: "Intellij+all",
      intellijiml: "Intellij+iml",
      ionic3: "Ionic3",
      jabref: "JabRef",
      janet: "Janet",
      java: "Java",
      jboss: "JBoss",
      "jboss-4-2-3-ga": "JBoss-4-2-3-GA",
      "jboss-6-x": "JBoss-6-x",
      jboss4: "JBoss4",
      jboss423ga: "JBoss-4-2-3-GA",
      jboss6: "JBoss6",
      jboss6x: "JBoss-6-x",
      jdeveloper: "JDeveloper",
      jekyll: "Jekyll",
      jenv: "JEnv",
      jetbrains: "JetBrains",
      "jetbrains+all": "JetBrains+all",
      "jetbrains+iml": "JetBrains+iml",
      jetbrainsall: "JetBrains+all",
      jetbrainsiml: "JetBrains+iml",
      jgiven: "JGiven",
      jigsaw: "Jigsaw",
      jmeter: "JMeter",
      joe: "Joe",
      joomla: "Joomla",
      jsonnet: "Jsonnet",
      jspm: "jspm",
      julia: "Julia",
      jupyternotebooks: "JupyterNotebooks",
      justcode: "JustCode",
      kaldi: "kaldi",
      kate: "Kate",
      kdevelop4: "KDevelop4",
      kdiff3: "KDiff3",
      keil: "Keil",
      kentico: "Kentico",
      keystonejs: "KeystoneJS",
      kicad: "KiCad",
      kirby2: "Kirby2",
      kirby3: "Kirby3",
      kobalt: "Kobalt",
      kohana: "Kohana",
      komodoedit: "KomodoEdit",
      konyvisualizer: "KonyVisualizer",
      kotlin: "Kotlin",
      labview: "LabVIEW",
      labviewnxg: "LabVIEWNXG",
      lamp: "LAMP",
      laravel: "Laravel",
      latex: "LaTeX",
      lazarus: "Lazarus",
      leiningen: "Leiningen",
      lemonstand: "LemonStand",
      less: "Less",
      liberosoc: "LiberoSOC",
      "librarian-chef": "librarian-chef",
      librarianchef: "librarian-chef",
      libreoffice: "LibreOffice",
      lighthouseci: "LighthouseCI",
      lilypond: "Lilypond",
      linux: "Linux",
      lithium: "Lithium",
      localstack: "LocalStack",
      logtalk: "Logtalk",
      lsspice: "LSspice",
      ltspice: "LTspice",
      lua: "Lua",
      lyx: "LyX",
      macos: "macOS",
      magento: "Magento",
      magento1: "Magento1",
      magento2: "Magento2",
      "magic-xpa": "Magic-xpa",
      magicxpa: "Magic-xpa",
      matlab: "MATLAB",
      maven: "Maven",
      mavensmate: "MavensMate",
      mdbook: "MdBook",
      mean: "MEAN",
      mercurial: "Mercurial",
      mercury: "Mercury",
      meson: "Meson",
      metals: "Metals",
      metalsmith: "Metalsmith",
      metaprogrammingsystem: "MetaProgrammingSystem",
      meteor: "Meteor",
      meteorjs: "MeteorJS",
      microsoftoffice: "MicrosoftOffice",
      mikroc: "MikroC",
      mill: "Mill",
      moban: "Moban",
      modelsim: "ModelSim",
      modx: "MODX",
      momentics: "Momentics",
      monodevelop: "MonoDevelop",
      mplabx: "MPLabX",
      mule: "mule",
      nanoc: "Nanoc",
      nativescript: "NativeScript",
      ncrunch: "NCrunch",
      nesc: "NesC",
      netbeans: "NetBeans",
      nette: "Nette",
      nextjs: "NextJS",
      nikola: "Nikola",
      nim: "Nim",
      ninja: "Ninja",
      node: "Node",
      nodechakratimetraveldebug: "NodeChakraTimeTravelDebug",
      nohup: "Nohup",
      notepadpp: "NotepadPP",
      nova: "nova",
      now: "now",
      nuxtjs: "NuxtJS",
      nwjs: "NWjs",
      "objective-c": "Objective-C",
      objectivec: "Objective-C",
      obsidian: "Obsidian",
      ocaml: "OCaml",
      octave: "Octave",
      octobercms: "OctoberCms",
      opa: "Opa",
      opencart: "OpenCart",
      opencv: "OpenCV",
      openfoam: "OpenFOAM",
      openframeworks: "OpenFrameworks",
      "openframeworks+visualstudio": "OpenFrameworks+VisualStudio",
      openframeworksvisualstudio: "OpenFrameworks+VisualStudio",
      oracleforms: "OracleForms",
      orcad: "OrCAD",
      osx: "OSX",
      otto: "Otto",
      oxideshop: "OxidEshop",
      oxygenxmleditor: "oXygenXMLEditor",
      packer: "Packer",
      pants: "Pants",
      particle: "Particle",
      patch: "Patch",
      pawn: "PAWN",
      perl: "Perl",
      perl6: "Perl6",
      ph7cms: "pH7CMS",
      phalcon: "Phalcon",
      phoenix: "Phoenix",
      "php-cs-fixer": "PHP-CS-Fixer",
      phpcodesniffer: "PHPCodeSniffer",
      phpcsfixer: "PHP-CS-Fixer",
      phpstorm: "PhpStorm",
      "phpstorm+all": "PhpStorm+all",
      "phpstorm+iml": "PhpStorm+iml",
      phpstormall: "PhpStorm+all",
      phpstormiml: "PhpStorm+iml",
      phpunit: "PHPUnit",
      pico8: "pico8",
      pimcore: "Pimcore",
      pimcore4: "Pimcore4",
      pimcore5: "Pimcore5",
      pinegrow: "PineGrow",
      platformio: "PlatformIO",
      playframework: "PlayFramework",
      plone: "Plone",
      polymer: "Polymer",
      powershell: "PowerShell",
      "premake-gmake": "premake-gmake",
      premakegmake: "premake-gmake",
      prepros: "Prepros",
      prestashop: "Prestashop",
      processing: "Processing",
      progressabl: "ProgressABL",
      psoccreator: "PSoCCreator",
      pulumi: "Pulumi",
      "pulumi+stacks": "Pulumi+stacks",
      pulumistacks: "Pulumi+stacks",
      puppet: "Puppet",
      "puppet-librarian": "puppet-librarian",
      puppetlibrarian: "puppet-librarian",
      purebasic: "PureBasic",
      purescript: "PureScript",
      putty: "PuTTY",
      pvs: "PVS",
      pycharm: "PyCharm",
      "pycharm+all": "PyCharm+all",
      "pycharm+iml": "PyCharm+iml",
      pycharmall: "PyCharm+all",
      pycharmiml: "PyCharm+iml",
      pydev: "pydev",
      python: "Python",
      pythonvanilla: "PythonVanilla",
      qml: "QML",
      qooxdoo: "Qooxdoo",
      qt: "Qt",
      qtcreator: "QtCreator",
      r: "R",
      racket: "Racket",
      rails: "Rails",
      react: "react",
      reactnative: "ReactNative",
      reasonml: "Reasonml",
      red: "Red",
      redcar: "Redcar",
      redis: "Redis",
      remix: "Remix",
      "remix+arc": "Remix+Arc",
      "remix+cloudflarepages": "Remix+CloudflarePages",
      "remix+cloudflareworkers": "Remix+CloudflareWorkers",
      "remix+netlify": "Remix+Netlify",
      "remix+vercel": "Remix+Vercel",
      remixarc: "Remix+Arc",
      remixcloudflarepages: "Remix+CloudflarePages",
      remixcloudflareworkers: "Remix+CloudflareWorkers",
      remixnetlify: "Remix+Netlify",
      remixvercel: "Remix+Vercel",
      renpy: "Renpy",
      replit: "replit",
      retool: "retool",
      rhodesrhomobile: "RhodesRhomobile",
      rider: "Rider",
      robotframework: "robotframework",
      root: "ROOT",
      ros: "ROS",
      ros2: "ROS2",
      ruby: "Ruby",
      rubymine: "RubyMine",
      "rubymine+all": "RubyMine+all",
      "rubymine+iml": "RubyMine+iml",
      rubymineall: "RubyMine+all",
      rubymineiml: "RubyMine+iml",
      rust: "Rust",
      "rust-analyzer": "rust-analyzer",
      rustanalyzer: "rust-analyzer",
      salesforce: "Salesforce",
      salesforcedx: "SalesforceDX",
      sam: "SAM",
      "sam+config": "SAM+config",
      samconfig: "SAM+config",
      sas: "SAS",
      sass: "Sass",
      sbt: "SBT",
      scala: "Scala",
      scheme: "Scheme",
      scons: "SCons",
      scrivener: "Scrivener",
      sdcc: "Sdcc",
      seamgen: "SeamGen",
      senchatouch: "SenchaTouch",
      serverless: "Serverless",
      shopware: "Shopware",
      silverstripe: "Silverstripe",
      sketchup: "SketchUp",
      slickedit: "SlickEdit",
      smalltalk: "Smalltalk",
      snap: "Snap",
      snapcraft: "Snapcraft",
      snyk: "Snyk",
      solidity: "Solidity",
      soliditytruffle: "SolidityTruffle",
      sonar: "Sonar",
      sonarqube: "SonarQube",
      sourcepawn: "SourcePawn",
      spark: "Spark",
      specflow: "SpecFlow",
      splunk: "Splunk",
      spreadsheet: "Spreadsheet",
      ssh: "SSH",
      standardml: "StandardML",
      stata: "Stata",
      stdlib: "StdLib",
      stella: "Stella",
      stellar: "Stellar",
      storybookjs: "StorybookJs",
      strapi: "Strapi",
      stylus: "Stylus",
      sublimetext: "SublimeText",
      sugarcrm: "SugarCRM",
      svelte: "Svelte",
      svn: "SVN",
      swift: "Swift",
      swiftpackagemanager: "SwiftPackageManager",
      swiftpm: "SwiftPM",
      symfony: "Symfony",
      symphonycms: "SymphonyCMS",
      synology: "Synology",
      synopsysvcs: "SynopsysVCS",
      tags: "Tags",
      tarmainstallmate: "TarmaInstallMate",
      terraform: "Terraform",
      terragrunt: "Terragrunt",
      test: "Test",
      testcomplete: "TestComplete",
      testinfra: "Testinfra",
      tex: "TeX",
      text: "Text",
      textmate: "TextMate",
      textpattern: "Textpattern",
      "theos-tweak": "THEOS-Tweak",
      theostweak: "THEOS-Tweak",
      thinkphp: "ThinkPHP",
      tla: "TLA+",
      "tla+": "TLA+",
      toit: "Toit",
      tortoisegit: "TortoiseGit",
      tower: "Tower",
      turbo: "Turbo",
      turbogears2: "TurboGears2",
      twincat3: "TwinCAT3",
      tye: "Tye",
      typings: "Typings",
      typo3: "Typo3",
      "typo3-composer": "TYPO3-composer",
      typo3composer: "TYPO3-composer",
      umbraco: "Umbraco",
      unity: "Unity",
      unrealengine: "UnrealEngine",
      vaadin: "Vaadin",
      vagrant: "Vagrant",
      valgrind: "Valgrind",
      vapor: "Vapor",
      vcpkg: "vcpkg",
      venv: "venv",
      vercel: "Vercel",
      vertx: "Vertx",
      video: "Video",
      vim: "Vim",
      virtualenv: "VirtualEnv",
      virtuoso: "Virtuoso",
      visualbasic: "VisualBasic",
      visualstudio: "VisualStudio",
      visualstudiocode: "VisualStudioCode",
      vivado: "Vivado",
      vlab: "VLab",
      vrealizeorchestrator: "vRealizeOrchestrator",
      vs: "vs",
      vue: "Vue",
      vuejs: "Vuejs",
      vvvv: "VVVV",
      waf: "Waf",
      wakanda: "Wakanda",
      web: "Web",
      webmethods: "WebMethods",
      webstorm: "WebStorm",
      "webstorm+all": "WebStorm+all",
      "webstorm+iml": "WebStorm+iml",
      webstormall: "WebStorm+all",
      webstormiml: "WebStorm+iml",
      werckercli: "WerckerCLI",
      windows: "Windows",
      wintersmith: "Wintersmith",
      wordpress: "WordPress",
      wyam: "Wyam",
      xamarinstudio: "XamarinStudio",
      xcode: "Xcode",
      xcodeinjection: "XcodeInjection",
      xilinx: "Xilinx",
      xilinxise: "XilinxISE",
      xilinxvivado: "XilinxVivado",
      xill: "Xill",
      xmake: "xmake",
      xojo: "Xojo",
      xtext: "XText",
      y86: "Y86",
      yalc: "yalc",
      yarn: "yarn",
      yeoman: "Yeoman",
      yii: "Yii",
      yii2: "Yii2",
      zendframework: "ZendFramework",
      zephir: "Zephir",
      zig: "zig",
      zsh: "Zsh",
      zukencr8000: "ZukenCR8000",
    };

    expect(result2).toEqual(expected2);
  });
});

describe("clean()", () => {
  test("clean()", () => {
    let input = "React";
    let expected = "react";

    const result = clean(input);
    expect(result).toEqual(expected);
  });

  test("clean()", () => {
    let input = "ASP.NETCORE++";
    let expected = "aspnetcore";

    const result = clean(input);
    expect(result).toEqual(expected);
  });
});

describe("fillTechOptionsDict()", () => {
  test("fillTechOptionsDict ", () => {
    const result = fillTechOptionsDict(techOptPrep, getTechoptionsList());
    let expected = techOptions;
    expect(result).toEqual(expected);
  });

  test("fillTechOptionsDict with some technologies equal after removing special characters ", () => {
    let allTechOptions = [
      "c",
      "c++",
      "c#",
      "csharp",
      "asp.netcore",
      "aspnetcore",
      "jetbrains+all",
      "react.js",
    ];

    let expected = {
      "asp.netcore": "asp.netcore",
      aspnetcore: "aspnetcore",
      c: "c",
      "c#": "c#",
      "c++": "c++",
      csharp: "csharp",
      "jetbrains+all": "jetbrains+all",
      jetbrainsall: "jetbrains+all",
      "react.js": "react.js",
      reactjs: "react.js",
    };

    const result = fillTechOptionsDict({}, allTechOptions);
    expect(result).toEqual(expected);
  });
});

describe("filterPrep()", () => {
  test("filterPrep ", () => {
    let expected1 = {
      "1c-bitrix": "1C-Bitrix",
      "a-frame": "A-Frame",
      adb: "Ada",
      ads: "Ada",
      "appcode+all": "AppCode+all",
      "appcode+iml": "AppCode+iml",
      as: "Actionscript",
      asm: "Assembler",
      "asp.netcore": "ASPNETCore",
      "autotools+strict": "Autotools+strict",
      "c#": "Csharp",
      "c++": "C++",
      cbp: "CodeBlocks",
      "clion+all": "CLion+all",
      "clion+iml": "CLion+iml",
      cpluplus: "C++",
      cpp: "C++",
      "cs-cart": "CS-Cart",
      "f#": "fsharp",
      "goland+all": "GoLand+all",
      "goland+iml": "GoLand+iml",
      hs: "Haskell",
      iar_ewarm: "IAR_EWARM",
      "intellij+all": "Intellij+all",
      "intellij+iml": "Intellij+iml",
      ipynb: "JupyterNotebooks",
      "jboss-4-2-3-ga": "JBoss-4-2-3-GA",
      "jboss-6-x": "JBoss-6-x",
      "jetbrains+all": "JetBrains+all",
      "jetbrains+iml": "JetBrains+iml",
      jl: "Julia",
      jsx: "react",
      kt: "Kotlin",
      "librarian-chef": "librarian-chef",
      "magic-xpa": "Magic-xpa",
      mps: "MetaProgrammingSystem",
      "next.js": "NextJS",
      npp: "NotepadPP",
      "nuxt.js": "NuxtJS",
      "objective-c": "Objective-C",
      "openframeworks+visualstudio": "OpenFrameworks+VisualStudio",
      p6: "Perl6",
      "php-cs-fixer": "PHP-CS-Fixer",
      "phpstorm+all": "PhpStorm+all",
      "phpstorm+iml": "PhpStorm+iml",
      pl: "Perl",
      "premake-gmake": "premake-gmake",
      ps: "PowerShell",
      "pulumi+stacks": "Pulumi+stacks",
      "puppet-librarian": "puppet-librarian",
      "pycharm+all": "PyCharm+all",
      "pycharm+iml": "PyCharm+iml",
      rb: "Ruby",
      rbrubymin: "RubyMine",
      "rbrubymin+all": "RubyMine+all",
      "rbrubymin+iml": "RubyMine+iml",
      "react.js": "react",
      reactjs: "react",
      "remix+arc": "Remix+Arc",
      "remix+cloudflarepages": "Remix+CloudflarePages",
      "remix+cloudflareworkers": "Remix+CloudflareWorkers",
      "remix+netlify": "Remix+Netlify",
      "remix+vercel": "Remix+Vercel",
      rkt: "Racket",
      rs: "Rust",
      "rubymine+all": "RubyMine+all",
      "rubymine+iml": "RubyMine+iml",
      "rust-analyzer": "rust-analyzer",
      "sam+config": "SAM+config",
      sch: "Eagle",
      scm: "Scheme",
      skp: "SketchUp",
      tf: "Terraform",
      "theos-tweak": "THEOS-Tweak",
      "tla+": "TLA+",
      "typo3-composer": "TYPO3-composer",
      vb: "VisualBasic",
      vscode: "VisualStudioCode",
      "vue.js": "Vuejs",
      "webstorm+all": "WebStorm+all",
      "webstorm+iml": "WebStorm+iml",
      wp: "WordPress",
    };
    const result1 = filterPrep(techOptPrep, getTechoptionsList());
    expect(result1).toEqual(expected1);
  });

  test("filterPrep with some conflicts between allTechOptions and techOptPrep", () => {
    let allTechOptions = [
      "As",
      "Asp.netcore",
      "C++",
      "CbP",
      "Sch++",
      "Actionscript",
      "Assembler",
      "ASPNETCore",
      "CodeBlocks",
      "Csharp",
      "Eagle",
    ];
    let techOptPrep = {
      adb: "Ada",
      ads: "Ada",
      as: "Actionscript",
      asm: "Assembler",
      "asp.netcore": "ASPNETCore",
      cbp: "CodeBlocks",
      cpluplus: "C++",
      cpp: "C++",
      "c#": "Csharp",
      sch: "Eagle",
    };
    const result = filterPrep(techOptPrep, allTechOptions);
    let expected = {
      asm: "Assembler",
      "asp.netcore": "ASPNETCore",
      "c#": "Csharp",
      cpluplus: "C++",
      cpp: "C++",
    };
    expect(result).toEqual(expected);
  });
});

describe("sortDictByValue()", () => {
  test("sortDictByValue()", () => {
    let input1 = {
      a: "3",
      b: "1",
      c: "2",
    };
    const result1 = sortDictByValue(input1);
    let expected1 = {
      b: "1",
      c: "2",
      a: "3",
    };
    expect(result1).toEqual(expected1);
  });
  test("sortDictByValue()", () => {
    let input2 = {
      x: "10",
      y: "5",
      z: "7",
    };
    const result2 = sortDictByValue(input2);
    let expected2 = {
      y: "5",
      z: "7",
      x: "10",
    };
    expect(result2).toEqual(expected2);
  });
});

describe("getLinksDict()", () => {
  test("getLinksDict()", () => {
    const result = getLinksDict();
    let expected = techOptFiles;
    expect(result).toEqual(expected);
  });
});

describe("getFilesForLink()", () => {
  let files: fs.Dirent[];
  beforeAll(() => {
    files = fs.readdirSync("./templates", {
      withFileTypes: true,
    });
  });
  test("getFilesForLink ReactNative", () => {
    const result = getFilesForLink(files, "ReactNative");
    let expected = [
      "Android.gitignore",
      "Android.patch",
      "Buck.gitignore",
      "Gradle.gitignore",
      "Gradle.patch",
      "Linux.gitignore",
      "Node.gitignore",
      "Node.patch",
      "Xcode.gitignore",
      "Xcode.patch",
      "ReactNative.gitignore",
      "macOS.gitignore",
      "macOS.patch",
    ];
    expect(result.sort()).toEqual(expected.sort());
  });

  test("getFilesForLink AppCode+all", () => {
    const result = getFilesForLink(files, "AppCode+all");
    let expected = [
      "JetBrains.gitignore",
      "JetBrains.patch",
      "JetBrains+all.patch",
    ];
    expect(result.sort()).toEqual(expected.sort());
  });
});

describe("sortDict()", () => {
  test("sortDict()", () => {
    const dict = {
      b: ["2", "6"],
      c: ["3", "4"],
      a: ["1", "5"],
    };
    const result = sortDict(dict);
    const expected = {
      a: ["1", "5"],
      b: ["2", "6"],
      c: ["3", "4"],
    };
    expect(result).toEqual(expected);
  });
});

describe("sortFiles()", () => {
  test("sortFiles()", () => {
    const files = [
      "macOS.patch",
      "Buck.gitignore",
      "Gradle.gitignore",
      "Linux.gitignore",
      "Node.gitignore",
      "ReactNative.gitignore",
      "Android.gitignore",
      "Gradle.patch",
      "macOS.gitignore",
      "Xcode.gitignore",
      "Android.patch",
      "Xcode.patch",
      "Node.patch",
    ];
    const result = sortFiles(files, "ReactNative");
    const expected = [
      "ReactNative.gitignore",
      "Android.gitignore",
      "Android.patch",
      "Buck.gitignore",
      "Gradle.gitignore",
      "Gradle.patch",
      "Linux.gitignore",
      "macOS.gitignore",
      "macOS.patch",
      "Node.gitignore",
      "Node.patch",
      "Xcode.gitignore",
      "Xcode.patch",
    ];
    expect(result).toEqual(expected);
  });
});
