name: deploy
run-name: Deploy to edgio, needs secret EDGIO_DEPLOY_TOKEN to be set
on:
  workflow_dispatch:

  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy-to-edgio:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.head_ref == 'update-tech-options'
    env:
      EDGIO_DEPLOY_TOKEN: ${{ secrets.EDGIO_DEPLOY_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy to edgio
        run: |
          npm run edgio:deploy --token=$EDGIO_DEPLOY_TOKEN
