name: deploy
run-name: Deploy to edgio

on:
  workflow_dispatch:

  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy-to-edgio:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && (github.head_ref == 'update-tech-options' || github.head_ref == 'main')
    env:
      EDGIO_DEPLOY_TOKEN: ${{ secrets.EDGIO_DEPLOY_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Deploy to edgio
        run: |
          npm run edgio:deploy --token=$EDGIO_DEPLOY_TOKEN
