name: deploy
run-name: Deploy to edgio

on:
  workflow_dispatch:

  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  deploy-to-edgio:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.head_ref == 'update-tech-options' || github.event_name == 'workflow_dispatch'
    env:
      EDGIO_DEPLOY_TOKEN: ${{ secrets.EDGIO_DEPLOY_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install

      - name: Clone toptal templates
        run: |
          git clone https://github.com/toptal/gitignore ./toptal.gitignoreTemplates

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: attr
          version: 1.0

      - name: Update github templates
        run: |
          cat ./toptal.gitignoreTemplates/.github/scripts/sync-github.sh
          bash ./toptal.gitignoreTemplates/.github/scripts/sync-github.sh

      # - name: debugging
      #   run:  |
      #     cd toptal.gitignoreTemplates
      #     ls -la
      # - name: debugging
      #   run:  |
      #     cd toptal.gitignoreTemplates/.github
      #     ls -la
      # - name: debugging
      #   run:  |
      #     cd toptal.gitignoreTemplates/templates
      #     ls -la




      #npm run edgio:deploy --token=$EDGIO_DEPLOY_TOKEN


      - name: Deploy to edgio
        run: |
          npx edgio deploy --property=gitignore --organization=profiq -e default --token=$EDGIO_DEPLOY_TOKEN
