name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  update-tech-options:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clone toptal templates
        run: |
          git clone https://github.com/toptal/gitignore ./totpal.gitignoreTemplates/gitignore

      - name: Update github templates
        run: |
          ls -la ./totpal.gitignoreTemplates/gitignore/.github/scripts
          cd ./totpal.gitignoreTemplates/gitignore/.github/scripts && bash ./sync-github.sh

      - name: Run the prebuild script
        run: node ./prebuild-scripts/update-list.mjs

      - name: Commit changes
        run: |
          git config --global user.name "FilipLunski"
          git config --global user.email "f.lunski@gmail.com"

          git add -A
          git commit -m "timestamp"
          git push
